export const UtilsData = {
    "Cuadernos Doble Líneas": "0",
    "Cuadernos  Mixtos": "0",
    "Cuadernos Cuadriculados": "0",
    "Cuaderno Preescolar Tipo A": "0",
    "Cuaderno Preescolar Tipo B": "0",
    "Cuaderno Preescolar Tipo C": "0",
    "Pentagramado": "0",
    "Block de Construcción": "0",
    "Block de Tesis": "0",
    "Block de Dibujo": "0",
    "Block de Papel Lustrillo": "0",
    "Cartulina Sencilla": "0",
    "Cartulina Doble Faz ": "0",
    "Lámina de Foami": "0",
    "Papel Bond ": "0",
    "Papel Crepe": "0",
    "Papel Pana": "0",
    "Papel Seda": "0",
    "Papel Celofán": "0",
    "Papel Lustrillo ": "0",
    "Creyón Bicolor": "0",
    "Caja de Creyones de Madera": "0",
    "Caja de Creyones de Cera": "0",
    "Caja de Creyones Plásticos": "0",
    "Caja de Lápices": "0",
    "Caja de Tempera": "0",
    "Caja de Plastilina": "0",
    "Caja de Tizas": "0",
    "Caja de Zapatos Forrada": "0",
    "Hojas de Examen ": "0",
    "Resma de Hojas Carta": "0",
    "Resma de Hojas Oficio": "0",
    "Carpeta Manila Carta": "0",
    "Carpeta Manila Oficio": "0",
    "Carpeta Marrón Carta:": "0",
    "Carpeta Marrón Oficio:": "0",
    "Sobre Manila Tipo:": "0",
    "Juego Geométrico": "0",
    "Regla": "0",
    "Compás": "0",
    "Estuche de Marcadores": "0",
    "Marcador para Pizarra Acrílica": "0",
    "Marcadores Finos": "0",
    "Marcadores Gruesos": "0",
    "Juego Didáctico": "0",
    "Arcilla": "0",
    "Rollo de Lana Escolar": "0",
    "Aguja Punta Roma": "0",
    "Escarcha": "0",
    "Fieltro": "0",
    "Frasco de Pega": "0",
    "Paletas de Helados": "0",
    "Pincel Fino": "0",
    "Pincel Grueso": "0",
    "Tijera Punta Roma": "0",
    "Sacapuntas con Depósito": "0",
    "Borrador": "0",
    "Etiquetas": "0",
    "Tubo de Pintadedos": "0",
    "Pote de Plastidedos": "0",
    "Tubo de Plasticola": "0",
    "Pote de Pintura al Frío": "0",
    "Tirro": "0",
    "Cinta Plástica": "0",
    "Delantal o Franela": "0",
    "Bulto o Morral": "0",
    "Cartuchera": "0",
    "Silicón Líquido": "0",
    "Barras de Silicón": "0",
    "Pañito": "0",
    "Jabón de Baño": "0",
    "Paquete de Servilletas": "0",
    "Toallin": "0",
    "Rollos de Papel Higiénico": "0",
    "Paquete de Vasos Plásticos Nº": "0",
    "Lonchera": "0",
    "Termo o Cantimplora": "0",
    "Medicamento para Primeros Auxilios": "0",
    "Material de Desecho": "0",
    "Pega en Barra": "0",
}
